@extends('layouts.home')

@section('conteudo')
    
    <div style="display: flex; justify-content: center;">
        <img src="/img/titulo1.png" width="80%"/>
    </div>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas auctor consectetur lorem. Maecenas et sodales risus. Fusce id urna eros. Maecenas finibus tempus lectus efficitur efficitur. Duis vitae augue ornare, sollicitudin nunc sed, pretium felis. Pellentesque cursus, nisi quis faucibus auctor, tellus erat pellentesque nisi, eget venenatis orci felis in dolor. Etiam pellentesque euismod urna sed ornare. Praesent justo purus, finibus sit amet suscipit eget, luctus sed nisl. Aenean semper facilisis tortor, blandit venenatis mauris vulputate vitae. Nunc faucibus eros ut nulla pellentesque, sit amet faucibus massa tristique.

        Phasellus luctus, massa vel cursus faucibus, risus nulla tincidunt quam, sollicitudin efficitur ex magna sit amet neque. Proin orci erat, sollicitudin sit amet dui id, consequat tincidunt ex. Nam scelerisque metus ipsum, quis tempus nisi mollis eu. Duis urna risus, ornare id lacus porta, gravida luctus tortor. Etiam ultricies ligula lorem. Phasellus ut suscipit turpis. In placerat ultrices urna, a semper turpis lobortis vitae. Etiam felis nisl, sollicitudin at imperdiet non, iaculis et nibh. Morbi molestie quam sit amet nisi malesuada, dignissim lacinia neque posuere. Curabitur vitae dictum leo. Proin et ultricies nunc. Morbi ac vulputate erat, a dapibus dui. Donec hendrerit mi sed nunc pellentesque, eleifend consequat libero ornare.

        Curabitur consectetur pulvinar convallis. Quisque vitae eleifend enim. Nullam vitae risus sed sem faucibus convallis. Nulla gravida cursus finibus. Quisque et magna tristique, consequat velit id, convallis quam. Proin dui eros, laoreet a consectetur at, molestie a neque. Fusce finibus eu mi maximus imperdiet. Nulla facilisi.

        Aenean non sollicitudin turpis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum eu tellus eu eros malesuada vulputate vitae a nisi. Nam urna nisi, tincidunt eget tincidunt in, eleifend vel dolor. Pellentesque laoreet lorem at justo venenatis, non ultricies diam finibus. Nam scelerisque vitae velit at placerat. Fusce mollis tempus suscipit. Nam vitae purus non augue congue vestibulum eget a enim. Donec enim felis, posuere elementum bibendum eget, viverra eget tortor. In vitae lacinia elit.

        Vivamus ipsum purus, accumsan quis sodales quis, vehicula at nulla. Nam faucibus magna malesuada neque ultricies blandit. Proin pharetra euismod sapien, nec faucibus elit tincidunt nec. Nam mattis auctor lorem eget tincidunt. Fusce cursus mauris non urna pulvinar, quis venenatis mi suscipit. Nam rutrum ultricies sapien id pharetra. Donec viverra dolor ac ultricies interdum. Donec porttitor dolor libero, faucibus fermentum lectus rutrum sed. Morbi feugiat condimentum lorem, a accumsan enim cursus eu. Sed eu tincidunt urna, in lacinia diam. Morbi leo ipsum, sodales sed nulla eget, finibus scelerisque arcu. Quisque pulvinar vel lectus ac rhoncus. Morbi condimentum vulputate ligula eu rhoncus.

        is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
        is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
        is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
        is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
        is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
        is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
        is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
        is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
        is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
        is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
        is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
        is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
    </p>

@endsection